global:
  src_path: './app'
  public_path: './public'
  styles_path: "{{ &global.public_path }}"
  scripts_path: "{{ &global.public_path }}"




###############
#  Stylus
#
#  Autoprefixer - Browser prefix
#  -webkit- prefix add 'safari 7'
#  -ms- prefix add 'ie 9'
#  -moz- prefix add 'firefox 20'
###############
stylus:
  autoprefixer:
    browsers:
      - 'ie 9'
      - 'ie 10'
      - 'ie 11'
  files:
    - "{{ &global.src_path }}/index.styl {{ &global.styles_path }}/main.css"




###############
#  SASS
###############
sass:
  files:
    - "{{ &global.src_path }}/index.sass {{ &global.styles_path }}/main.css"



###############
#  POSTCSS
###############
postcss:
  files:
    - "{{ &global.src_path }}/index.css {{ &global.styles_path }}/main.css"





###############
#  Babelify
###############
babelify: &babelify
  modules: common
  compact: false
  comments: false



###############
#  Aliasify
###############
aliasify: &aliasify
  aliases:
    core: "./app/scripts/core"
    sections: "./app/sections"
    modals: "./app/modals"
    components: "./app/components"
    common: "./app/scripts/common"
    mixins: "./app/scripts/mixins"
    observers: "./app/observers"
    mediators: "./app/mediators"





###############
#  Partialify
###############
partialify: &partialify
  extensions:
    - svg
    - txt





###############
#  Browserify
###############
browserify:
  files:
    - "{{ &global.src_path }}/index.js {{ &global.scripts_path }}/main.js"
    - "{{ &global.src_path }}/vendor/index.js {{ &global.scripts_path }}/vendor.js"
  options:
    cache: {}
    packageCache: {}
    extensions:
      - .js
      - .es
  babelify: *babelify
  partialify: *partialify
  aliasify: *aliasify





###############
#  Watch
###############
watcher: &watcher
  files:
    - "{{ &global.public_path }}/**/*"






###############
#  Server (Browser Sync)
###############
server:
  <<: *watcher
  proxy: http://localhost:3000/
  open: false





###############
#  Uglify
###############
uglify:
  files:
    - "{{ &global.scripts_path }}/main.js {{ &global.scripts_path }}/main.js"
    - "{{ &global.scripts_path }}/vendor.js {{ &global.scripts_path }}/vendor.js"






##############
# TEMPLATE
#
# eg : node ./workflow section MySectionName
##############
template:
  section:
    output: index
    destination_path: "{{ &global.src_path }}/sections"
    files:
      - section.html
      - stylus/section.styl
      - js
  component:
    destination_path: "{{ &global.src_path }}/component"
    files:
      - stylus/section.styl
      - js/section.js

